Add option to use storybook with more than one user
kadirahq/react-native-storybook pull request #132
Opened 2017-03-22 15:23 UTC by Gongreg

# Add option to differentiate connected users
We really like what storybook has to offer. We are going to use it to host our styleguide examples. We didn't like option to use react native web, we wanted users to be able to feel components in their phone. But react-native-stylebook doesn't support more than one user at the time. That is why I added options necessary to be able to host react-native-storybook in server and allow users play with the components.

Some work in progress, but in this gif you can see that we have one styleguide server running, two simulators and two browsers. User enters the code he sees (later on it could be QR code or anything else) and then he can play with his app without interupting others.

![Two simulators, two browsers one server playing together](https://media.giphy.com/media/3oKIPhYRUyUO5I6pWw/giphy.gif)

## I've added some command parameters:
* --reset-cache (simply passes option to react-native cli, when developing it sometimes makes difficult hard to debug, because it likes to cache things).
* --skip-packager (skip react-native packager all together and start only storybook server).
* --manual-id (tells storybook that now users should get custom id which they have to use in react-native app to connect to storybook. It allows to deploy storybook server to any host and tell users to download the app and enter code to play with it. If this flag is not passed, everything works same way as before. When user opens storybook he gets his own custom id and that id is sent through websocket query to be saved in server.).

## Also one bug fixed:
Story view component unmounts its events listeners when it is not rendered anymore.

2017-03-22 19:03 UTC, Gongreg commented
If somebody is going to be interested, we will try to add example project to github in few days.

2017-03-23 00:51 UTC, thani-sh requested changes

2017-03-23 00:51 UTC, mnmtanish commented on src/preview/index.js
> +        const url = `ws://${host}:${port}/${params.query}`;
If `params.query` is not set, the url will have `/undefined` in the end. Better set it to an empty string if it's not set.

```
const query = params.query || '';
const url = `ws://${host}:${port}/${query}`;
```

2017-03-23 00:56 UTC, mnmtanish commented
Hi @Gongreg 
I think this will be a useful feature. Can you add a simple step-by-step guide on how to use it including adding the `--manual-id`, starting react-native packagers and setting the id in the mobile app.

2017-03-23 08:54 UTC, Gongreg commented
Hey, today I will upload example project with readme about running the project.

I will also add option to run the server without running webpack.

2017-03-23 08:55 UTC, Gongreg commented on src/preview/index.js
> +        const url = `ws://${host}:${port}/${params.query}`;
Nice catch, thanks :)

2017-03-23 19:46 UTC, Gongreg commented
@mnmtanish Updated the initial comment, added example project. I will be waiting for your response.

2017-03-24 00:20 UTC, thani-sh approved these changes

2017-03-27 10:28 UTC, Gongreg commented
Hey, so what is going to happen next? Do I need to do something or I can just wait for PR to go into the master?

2017-03-28 00:23 UTC, merged

2017-03-28 00:25 UTC, mnmtanish commented
Hi @Gongreg, just released `v2.3.0` with this feature.

2017-03-28 06:44 UTC, Gongreg commented
Thank you very much :).
By any chance maybe you also work with @kadira/storybook-addon-knobs ? I created a PR over there. And I also see that @mthuret is working in storybooks team. She has a repo storybook-addon-usage. Maybe by any chance you can also ping her to look into it? I just don't want to create seperate repos doing same thing as existing ones.